#!/bin/bash

set -e

GOSACONF="/etc/fusiondirectory/fusiondirectory.conf"

if [ -e $GOSACONF ]; then
    exit 0
fi

fcopy -m root,www-data,0660 $GOSACONF

fcopy -m root,root,0770 /usr/local/sbin/gosa-create
fcopy -m root,root,0770 /usr/local/sbin/gosa-sync
fcopy -m root,root,0770 /usr/local/sbin/gosa-remove
fcopy -m root,root,0770 /usr/local/sbin/fd-sync
fcopy -m root,root,0770 /usr/local/sbin/add2gosa

fcopy /var/www/index.html

# set variables for files

FILES="/usr/local/sbin/gosa-create /usr/local/sbin/debian-lan /usr/local/sbin/add2gosa /var/www/index.html $GOSACONF"

for file in $FILES; do
    $ROOTCMD sed -i s#@LDAP_DOMAIN@#$LDAP_DOMAIN#g "$file"
    $ROOTCMD sed -i s#@SETDOMAIN@#$SETDOMAIN#g "$file"
    $ROOTCMD sed -i s#@KRB_REALM@#$KRB_REALM#g "$file"
done

## Insert password:
PWFILE="$DATADIR/LDAPadminPWD"
PW=`cat $target/$PWFILE`
sed -i "s#@LDAP_ADMIN_PW@#$PW#" $target/$GOSACONF

## Encrypt password:
# $ROOTCMD fusiondirectory-setup --check-config --yes

## needed for sudo-ldap:
ainsl /etc/ldap/ldap.conf "sudoers_base ou=sudoers,$LDAP_DOMAIN"
