#!/bin/bash

set -e

GOSACONF="/etc/fusiondirectory/fusiondirectory.conf"

if [ -e $GOSACONF ]; then
    exit 0
fi

fcopy -m root,www-data,0660 $GOSACONF

fcopy -m root,root,0770 /usr/local/sbin/gosa-create
fcopy -m root,root,0770 /usr/local/sbin/gosa-sync
fcopy -m root,root,0770 /usr/local/sbin/gosa-remove
fcopy -m root,root,0770 /usr/local/sbin/fd-sync
fcopy -m root,root,0770 /usr/local/sbin/add2gosa

wget https://github.com/twbs/bootstrap/releases/download/v3.3.4/bootstrap-3.3.4-dist.zip --no-check-certificate -O $target/var/www/bootstrap.zip
unzip $target/var/www/bootstrap.zip -d $target/var/www/

# FIXME - better permissions
chmod -R 777 $target/var/www/bootstrap-3.3.4-dist/

fcopy /var/www/index.html

# set variables for files

FILES="/usr/local/sbin/gosa-create /usr/local/sbin/debian-lan /usr/local/sbin/add2gosa /var/www/index.html $GOSACONF"

for file in $FILES; do
    $ROOTCMD sed -i s#@LDAP_DOMAIN@#$LDAP_DOMAIN#g "$file"
    $ROOTCMD sed -i s#@SETDOMAIN@#$SETDOMAIN#g "$file"
    $ROOTCMD sed -i s#@KRB_REALM@#$KRB_REALM#g "$file"
done

## Insert password:
PWFILE="$DATADIR/LDAPadminPWD"
PW=`cat $target/$PWFILE`
sed -i "s#@LDAP_ADMIN_PW@#$PW#" $target/$GOSACONF

# Insert LDAP admin password in dhcpd.conf 
sed -i "s#@LDAP_ADMIN_PW@#$PW#" $target/etc/dhcp/dhcpd.conf

## Encrypt password:
# $ROOTCMD fusiondirectory-setup --check-config --yes

## needed for sudo-ldap:
ainsl /etc/ldap/ldap.conf "sudoers_base ou=sudoers,$LDAP_DOMAIN"
