#!/bin/bash

set -e

## faiconfig:
fcopy -ir /etc/fai

## authorized_keys for root:
fcopy -ir /root

## Fetch proxy information from wpad.dat:
WPAD=/tmp/wpad.dat
http_proxy=""; wget --output-document=$WPAD http://wpad.${SETDOMAIN}/wpad.dat
PROXY=`cat $WPAD | grep PROXY | sed "s/^.*PROXY //" | sed "s/;.*$//"`
ainsl /etc/environment "http_proxy=http://$PROXY/"

if [ "$PROXY" == "webcache:8080" ] ; then
    ## dansguardian is used, lock iceweasel proxy configuration:
    ainsl /etc/iceweasel/pref/iceweasel.js 'lockPref("network.proxy.type", 4);'
else
    ## default configuration to wpad.dat proxy:
    ainsl /etc/iceweasel/pref/iceweasel.js 'pref("network.proxy.type", 4);'
fi

## Allow SSO in iceweasel:
ainsl /etc/iceweasel/pref/iceweasel.js "pref(\"network.negotiate-auth.delegation-uris\", \"${SETDOMAIN}\");"
ainsl /etc/iceweasel/pref/iceweasel.js "pref(\"network.negotiate-auth.trusted-uris\", \"${SETDOMAIN}\");"

## Default Homepage:
ainsl /etc/iceweasel/pref/iceweasel.js "pref(\"browser.startup.homepage\", \"data:text/plain,browser.startup.homepage=http://www.${SETDOMAIN}\");"

## Switch off caching over the network (commented, managed by unburden-home-dir now):
#ainsl /etc/iceweasel/pref/iceweasel.js 'pref("browser.cache.disk.enable", false);'
ainsl /etc/iceweasel/pref/iceweasel.js 'pref("browser.cache.offline.enable", false);'
#ainsl /etc/iceweasel/pref/iceweasel.js 'pref("browser.safebrowsing.enabled", false);'
#ainsl /etc/iceweasel/pref/iceweasel.js 'pref("browser.safebrowsing.malware.enabled", false);'
