#!/bin/bash
# /etc/init.d/owncloud-setup
#

# Some things that run always


echo "Starting script owncloud-setup"
mysql -u root -p@MYSQLROOTPW@ < /root/create-grant-owncloud.sql
mysql -u root -p@MYSQLROOTPW@ owncloud < /root/owncloud_start.sql

# rm /root/create-grant-owncloud.sql
# rm /root/owncloud_start.sql

exit 0

