#!/bin/bash

FAIDIR="$target/srv/fai/config/class"

cat >> $FAIDIR/SVERIGELINUX.var << EOF
# Log user to store fai log files to remote
LOGUSER="fai"
# LDAP 
LDAP_DOMAIN="$LDAP_DOMAIN"
# Domain name for the installation
SETDOMAIN="$SETDOMAIN"
# Kerberos realm for the installation
KRB_REALM="$KRB_REALM"
# Set default root password
ROOTPW=\'$ROOTPW\'

EOF
