#!/bin/bash

# add a demo user account
if [ -n "$ROOTPW" ] && ! $ROOTCMD getent passwd demo ; then
    $ROOTCMD adduser --disabled-login --gecos "Workplays" workplays
    $ROOTCMD usermod -p "$ROOTPW" workplays
fi
