#!/bin/bash

# add a demo user account
if [ -n "$ROOTPW" ] && ! $ROOTCMD getent passwd sverigelinux ; then
    $ROOTCMD adduser --disabled-login --gecos "SverigeLinux" sverigelinux
    $ROOTCMD usermod -p "$ROOTPW" sverigelinux
fi
