#!/bin/bash
#
# setup the diskless+swap server
#

fcopy /usr/local/sbin/nbdswapd
fcopy /etc/nbd-server/conf.d/swap.conf

ainsl /etc/exports "/opt              ${SUBNETMASK}(async,ro,no_subtree_check,no_root_squash)"
